name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: LeonTG
description: Using /ti, people can open a inventory shared between their team.

commands:
  teaminv:
    description: Open the team inventory.
    aliases: [ti]